Bugfix + Feature
hbz/laser2 pull request #310
Opened 2021-06-14 12:06 UTC by Moetez16

2021-06-14 12:13 UTC, croqueGrec09 commented on grails-app/services/de/laser/SubscriptionService.groovy
> +                case "laufzeit-beginn":
I would let start/enddatum accepted, too

2021-06-14 12:14 UTC, croqueGrec09 commented on grails-app/services/de/laser/SubscriptionService.groovy
> -                mappingErrorBag.multipleLicenseError = []
Warning with bulk objects! The error may concern several subscriptions, too!

2021-06-14 12:15 UTC, croqueGrec09 commented on grails-app/services/de/laser/SubscriptionService.groovy
> +                        mappingErrorBag.noPerpetualAccessType = hasPerpetualAccessKey
needs to be multiple, too

2021-06-14 12:15 UTC, croqueGrec09 commented on grails-app/services/de/laser/SubscriptionService.groovy
> +                        mappingErrorBag.noPublishComponent = hasPublishComponentKey
needs to be multiple, too

2021-06-14 12:15 UTC, croqueGrec09 commented on grails-app/services/de/laser/SubscriptionService.groovy
> +                        mappingErrorBag.noPublicForApi = isPublicForApiKey
needs to be multiple, too

2021-06-14 12:16 UTC, croqueGrec09 commented on grails-app/services/de/laser/SubscriptionService.groovy
> +            if(colMap.notes != null && cols[colMap.notes]) {
You permit empty values

2021-06-14 12:18 UTC, croqueGrec09 requested changes
cases when errors concern multiple subscriptions are not considered

2021-06-14 13:21 UTC, croqueGrec09 commented on grails-app/services/de/laser/SubscriptionService.groovy
> +                mappingErrorBag.multipleLicError = []
Is output corrected?

2021-06-14 15:14 UTC, Moetez16 commented on grails-app/services/de/laser/SubscriptionService.groovy
> +                mappingErrorBag.multipleLicError = []
Yes, the message property has this name.

2021-06-14 16:08 UTC, Moetez16 commented
PR geupdatet with new Bugfixes

2021-06-15 05:17 UTC, croqueGrec09 approved these changes
approved

2021-06-15 05:18 UTC, merged